name: deploys sample homepage
on: [push, pull_request]
jobs:
  run_first_job:
    runs-on: self-hosted
    steps:
      - name: confirm identity of the OS
        run: whoami
      - name: check out code from github to runner
        uses: actions/checkout@v5
      - name: deploy to nginx
        run: |
          cp $GITHUB_WORKSPACE/index.html /var/www/html/index.html
          echo "deploy succesful"
        
